- static/css/style.css
I were going to clean out some unused classes in the CSS, but it will be a pain to do it on minified CSS. Could we have style.css with whitespace in the repo and leave asset minimizing to build tools like Gulp?
I've run [prettier](https://prettier.io/) on style.css in this commit.
I'm sorry for my two earlier PRs, they included some erroneous commits.
> Ran prettier on style.css

- layouts/partials/header.html
Looking into [Hemingway](https://github.com/tanksuzuki/hemingway/) I found a [PR](https://github.com/tanksuzuki/hemingway/pull/2) that applies to kiss custom css property.
> relURL changed to absURL for custom css

- layouts/partials/header.html
Apparently this was introduced in 59d4984, possibly a mistake? All other URLs contain a `/` afterwards so I added this one back.
> Fix stylesheet URL

- layouts/partials/header.html
- layouts/partials/nav.html
This will add a second nav bar under site name,
with entries from params.sections.
If you don't add these params, generated markup will be exactly like before
Example:
```
[params.sections]
"/" = "~/"
"/posts" = "Posts"
"/projects" = "Projects"
```
>  Use params.sections (if present) for sections

- layouts/partials/nav.html
Hi,
those social links need `aria-label` for accessability.
Cheers
midzer
> improve accessability

- README.md
- layouts/partials/nav.html
Basically you can define something like this 
```
[[params.static]]                                                                                                                                                                                            
title = "Slides"
url = "http://slides.mateimicu.com"
```
and it will show up like this:
And of course you can add multiple links:
```
[[params.static]]                                                                                                                                                                                            
title = "Slides"
url = "http://slides.mateimicu.com"
[[params.static]] …
```
> Add the ability to link static elements in the nav

- layouts/index.html
- static/css/style.css
> Removed invisible margin which caused titles to wrap

- README.md
- layouts/index.html
Fixes #27. 
Uses frontmatter in page to hide page from list i.e:
```hidden: true```
Needed to add $paginator to ensure Paginate option is properly respected
> Added option to hide pages from list view

- README.md
- exampleSite/config.toml
- layouts/partials/nav.html
Resolves #54.
Downside is that the icons will be lost for all users that don't put `params.social.config` in their `config.toml`
> Add sorting for social icons

- layouts/index.html
We don't use fontawesome in the template so I guess the extra span for
fontawesome icon after "Read more" text can be removed. This will
also fix the extra spaces at the end of the link when you hover over it.
> Remove fontawesome icon in "Read more" link

- README.md
- exampleSite/config.toml
- layouts/partials/disqus.html
Disqus often makes them fast static websites slow to complete loading. I tried to add an optional configurable feature to allow loading Disqus comments on demand instead. Wdyt?
> Add disqus comment loading on demand

- layouts/partials/disqus.html
It would be great to have an option to disable comments on specific pages like about.
> Provide a parameter to disable disqus in a specific page

- layouts/index.html
- static/css/style.css
This makes it look better on phones / smaller windows.
**Before:**
**After:**
> Bigger line height in tags and date

- layouts/partials/header.html
Add canonical url into head tag for SEO.
> Add canonical url into head tag

- layouts/taxonomy/tag.html
A slightly modified copy of contents from the `index.html` template so that tag pages are rendered with only relevant articles.
Closes: #75
> Add taxonomy template for tag pages

- static/css/style.css
the default `style.css` file in the kiss theme file didn't differentiate
between code with and without syntax highlighting. as a result, using
the Chroma syntax highlighter doesn't inherit the foreground and
background color of the chosen theme.
the `<code>` element generated by Chroma has an attribute called
`data-lang` whose value is the programming language being highlighted.
we can use `data-lang` in a CSS selector to make Chroma generated `<code>`
inherit the background and foreground color from the theme being used.
> fixed the syntax highlighting done by chroma

- README.md
- exampleSite/config.toml
- layouts/index.html
- layouts/partials/taxonomies_count.html
I wanted to show post's number per taxonomies, so I PR that feature.
User can select whether to show number or not.
<br/>
> add taxonomies counter

- layouts/partials/tags.html
Hi,
for navigation it is better to have directory links closed:
`/tags/computers/` instead of `/tags/computers`
Cheers
midzer
> close url in tag links

- exampleSite/content/post/migrate-from-jekyll.md
- layouts/partials/analytics/matomo.html
- layouts/partials/header.html
- layouts/partials/social/opengraph.html
This PR fixes a few img, meta and link tags and removes the closing end as there is none in HTML5.
> tags should not be self-closing in HTML5 (closes #109)

- README.md
- exampleSite/config.toml
- layouts/partials/gfonts.html
- layouts/partials/header.html
- layouts/partials/math.html
I added the support of math equations and Google fonts. Both Mathjax and Katex are supported.
To enable Mathjax, edit `config.toml` to set `mathjax = true` or only set it in the front matter for a specific post. Katex as well.
Both should not be enabled at the same time.
`$$` is used for math block and `$` for inline math. For example:
```
$$
E = mc^2
$$
```
or `$E=mc^2$`.
There is no cost if disabled.
Google fonts can be used for custom font-family. For example, edit `config.toml`:
```toml
[params.assets]
googleFonts = ["Quicksand", "Open Sans"]
customCSS = ["css/custom.css"]
```
`/static/css/custom.css`:
```
body,
button,
input,
select,
textarea {
font-family: Quicksand, "Open Sans", Helvetica, Tahoma, Arial, STXihei, sans-serif;
}
```
There is no cost if `googleFonts` is an empty list.
> Added math equations and google fonts support

- README.md
- layouts/partials/header.html
I extended the `header.html` such that additional CSS and JS files are included when declared in the single page configuration.
> Name additional CSS and JS files in single page configuration
